### ISSUE TITLE
adding thredds param to core

### ISSUE THREAD

**Issue by lbesnard** [aodn/python-aodncore#103]
the ACORN handler needs to download data from the thredds server.
see
https://github.com/aodn/python-aodndata/pull/43#discussion_r195954616

Depending on the environment, RC, Prod or stack, this needs to be somehow transparent to the aodndata package

**Comment by mhidas** [comment]
I don't think this really need to be in core. As @lwgordonimos suggests [here](https://github.com/aodn/python-aodndata/pull/43/files/dcbdcf12b9d87dcf5dc2055a2a69dc8374be8467#r195954616), it's very easy to add it as a custom_param to the few specific handlers that need it.

**Comment by lbesnard** [comment]
in that case how do you make the difference between thredds-rc.aodn, thredds.aodn, thredds-stack ? if you add a custom_param, it means you have to create a different json file for different machines/environments. We don't do it for any other pipelines

**Comment by mhidas** [comment]
Yeah, sorry. I was just realising that. Never mind.

**Comment by lwgordonimos** [comment]
Resolved by https://github.com/aodn/python-aodncore/pull/104
