### ISSUE TITLE
The CHECK step should be multithreaded

### ISSUE THREAD

**Issue by lwgordonimos** [aodn/python-aodncore#150]
This is an example of a fairly typical handling of a manifest file containing 2048 files.

The entire processing takes 36 minutes, with the check step taking up 31 minutes(!) of this. Even though checking a file takes a bit under 1 second, when run in serial for manifest files this is a long time to wait, especially when the actual harvesting/publishing step takes 5 minutes for these files.

This can be identified by the *difference* between the timestamps of when the handler transitioned to HANDLER_PREPROCESSED and HANDLER_CHECKED.

```
2019-03-01 16:42:36,981 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_INITIALISED
2019-03-01 16:42:43,616 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_RESOLVED
2019-03-01 16:42:43,617 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_PREPROCESSED
2019-03-01 17:13:43,822 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_CHECKED
2019-03-01 17:13:43,823 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_PROCESSED
2019-03-01 17:18:45,007 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_PUBLISHED
2019-03-01 17:18:45,008 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_POSTPROCESSED
2019-03-01 17:18:45,366 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_NOTIFIED_SUCCESS
2019-03-01 17:18:45,366 SYSINFO tasks.SRS_SURFACE_WAVES[fcb70c42-629c-493a-8563-a5f556cc4c20] GenericHandler transitioned to state: HANDLER_COMPLETED_SUCCESS
```

This could be greatly reduced by running the checks in parallel. Even a thread pool of 10 would likely be enough to drastically reduce the time spend checking.

**Comment by lwgordonimos** [comment]
Of note, this wasted time cause Chef cooking to fail when these pipelines are very active, since it times out before the file is finished processing.

1. Chef sends stop signal
1. pipeline tries to finish the current file
1. Chef times out and fails
1. pipeline finishes current file and stops
1. pipeline stays stopped until manually started, or Chef runs again and restarts it

**Comment by mhidas** [comment]
@lwgordonimos What are your thoughts on this, after having had a go at implementing asynchronous checking (#151)? Is it worth keeping this as a potential future enhancement, or just live with the slowness of sequential checking?

Would it be easier to find a work-around for the case where a long-running pipeline blocks the Chef cooking? (Note that pipelines can take a long time for reasons other than compliance checking...)

**Comment by lwgordonimos** [comment]
As it stands, with the "everyone on one server" approach, it was not feasible. Because it is an IO task, it hits the limitation with the Global Interpreter Lock, which means it can't be multi-*threaded*.

It was definitely possible to perform parallel checking with multiple *processes*, however this created the situation where the peak load increased exponentially, with each pipeline potentially consuming 100% of multiple CPU cores, and grinding the whole server to a halt.

If the pipelines are able to be isolated from each other (e.g. containerised with workers separated from the batch processing and each other), then it could be feasible to allow the check step to spawn multiple processes to speed it up, but that depends on the re-architecture of the pipeline to occur first.

> Would it be easier to find a work-around for the case where a long-running pipeline blocks the Chef cooking?

I actually can't recall that happening for a long time. The solution is really to avoid huge manifest files and set a reasonable cap on the number of files being handled at once.

It was never really a problem to process a few thousand files (or even 10 or 20 thousand), but the one's that blocked were trying to do 100s of thousands in one go. This improved by the optimisation noted here: https://github.com/aodn/PO-Backlog/issues/1158, to stop running duplicate checks every time a collection is filtered internally), by making the increase in time to process much more linear with the number of files, but the smaller the chunks the better really.

**Comment by mhidas** [comment]
> Because it is an IO task, it hits the limitation with the Global Interpreter Lock, which means it can't be multi-threaded.

Hmm... not sure I understand this. I read up a bit about the GIL last week ([here](https://realpython.com/python-gil/#the-impact-on-multi-threaded-python-programs)). It's only a basic explanation, but it did say:
> The GIL does not have much impact on the performance of I/O-bound multi-threaded programs as the lock is shared between threads while they are waiting for I/O.

But it doesn't really matter. I agree the easier solution for now is to limit the number of files processed at a time.

**Comment by lwgordonimos** [comment]
That sentence is weird and self-contradictory, but the sentences immediately surrounding it actually explain the issue.

> In the multi-threaded version the GIL prevented the CPU-bound threads from executing in parellel.

> But a program whose threads are entirely CPU-bound, e.g., a program that processes an image in parts using threads, would not only become single threaded due to the lock but will also see an increase in execution time, as seen in the above example, in comparison to a scenario where it was written to be entirely single-threaded. 

If there are two or more concurrent threads, there is always only one actually doing anything at any given time, since they require the global lock (in this case to open the NC file and check it). This meant that it added a bunch of complexity for zero performance gain (or even a performance loss), since the threads had to run effectively in serial anyway, with the added overheads of managing threads.

The multi processing solution means spawning a pool of new processes (i.e. more Python interpreters, each with their own global lock) which does allow the work to be done in parallel, but at the expense of high and unpredictable load.
