### ISSUE TITLE
module version error on RC

### ISSUE THREAD

**Issue by bpasquer** [aodn/python-aodncore#170]
Running ANFOG_RT and SOOP_CO2 handler output the following error: 
`IncomingFileStateManager.state -> 'FILE_IN_PROCESSING'
2019-09-25 12:39:20,429 ERROR tasks.ANFOG_RT[7113df93-34c7-4367-a3e3-fd7b41cda49c] ImportError: 'module' object has no attribute '__version__'`

**Comment by lbesnard** [comment]
This is on 4-nec-hob. looking like it's affecting all pipelines blocking PO's in doing any sort of testing
FYI
@ccmoloney @pmbohm @ggalibert @mhidas

**Comment by mhidas** [comment]
This was promptly resolved at the time (https://github.com/aodn/issues/issues/537), but we forgot to close this issue.
