### ISSUE TITLE
Ability to query the harvest database (e.g.) to handle obsolete files

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodncore#47]
For some handlers it would be helpful to be able to query the harvest database, in order to find out about previously published files. The main use case is to allow the handler to identify and remove files that have been made obsolete by newer versions it has just published. This is to prevent users downloading duplicate versions of the same data, which would be confusing.

The query could be done either directly (requiring management of database credentials & connections), or via geoserver WFS.

**Comment by mhidas** [comment]
From @lwgordonimos:

Interesting summary article of the different approaches (I'm sure there are thousands more).

https://www.agile-code.com/blog/direct-sql-access-vs-web-service/

Obviously all of the security concerns around writes to the DB are irrelevant, but there are certainly still several tangible benefits to the service approach.

* connection management (pooling etc.)
* the need to handle authentication is removed
* enforcing predictable load patterns (e.g. since queries only need to be optimised for standard WFS requests, rather than potentially arbitrary SQL)
* abstraction from DB internals (e.g. any schema changes don't need to be reflected in both Geoserver AND pipeline)

**Comment by lwgordonimos** [comment]
Closed by: https://github.com/aodn/backlog/issues/980
