### ISSUE TITLE
Add option to purge file from error directory once successfully published

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodncore#51]
Sometimes a file with a given name is uploaded multiple times, with multiple copies of it ending up in the error directory. If the file is eventually fixed up and published successfully, it would be helpful if the handler could automatically remove previous versions of the same file (same name, possibly different content) from the error directory. This is currently done in some v1 pipelines (e.g. aodn/data-services#596)

**Comment by lwgordonimos** [comment]
This was implemented by https://github.com/aodn/python-aodncore/pull/117
