### ISSUE TITLE
listing of files in the upload location

### ISSUE THREAD

**Issue by bpasquer** [aodn/python-aodncore#56]
Some pipeline( ANFOG_DM, ANFOG_RT) need to access the upload location, whether it is S3 or a local directory to get a listing of the files/objects. This should be handle in the core instead of within single handler. A use case is for example ANFOG_DM  where all the realtime files related to the newly uploaded delayed mode deployment need to be deleted.

**Comment by mhidas** [comment]
@bpasquer Can this be closed now?
