### ISSUE TITLE
Ability to define destination path to archive the input_file

### ISSUE THREAD

**Issue by bpasquer** [aodn/python-aodncore#63]
The parameter "archive_input_file" in the Handlerbase class provides the ability to automatically archive input files, but the destination path 
 is set to "ARCHIVE_URI/PIPELINE_NAME/BASENAME"
by default. We should have the option to set a different path.

**Comment by pblain** [comment]
Added to backlog: https://github.com/aodn/backlog/issues/842
Closing this issue to avoid duplication
